"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=vrtxz5sx++4j8!!hsxp^hqyb72rd4sgq6=+5a2b13k7-i3u6h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'Online_Emporium',
    'crispy_forms',
    'rest_framework',
    'multiupload',
    'django_pandas',
    'social_django', 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'sslserver',
    "djstripe",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]


ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
    
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_database',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': 3306,
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '1087040574897-b9tr9htdj3g1rk2ns76banu39a48dnsf.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    
    
 
    
    }

SITE_ID = 1


# Use the SMTP email backend for sending emails.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND_ASYNC = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND_SYNC = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP Email Configuration
EMAIL_HOST = 'smtp.gmail.com'  
EMAIL_PORT = 465  
EMAIL_USE_SSL = True  #

# Your SMTP server credentials
EMAIL_HOST_USER = 'habibeternal@gmail.com'  
EMAIL_HOST_PASSWORD = 'tcly upwr klmk dznv'  

# From email address for sending emails
DEFAULT_FROM_EMAIL = 'habibeternal@gmail.com'
SERVER_EMAIL = 'habibeternal@gmail.com'


ACCOUNT_EMAIL_REQUIRED = True 
#ACCOUNT_UNIQUE_EMAIL = True
#ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_LOGIN_ATTEMPTS_TIMEOUT = 300


AUTH_USER_MODEL = 'Online_Emporium.CustomUser'
LOGIN_REDIRECT_URL = 'customer_dashboard'
SIGNUP_REDIRECT_URL = 'customer_dashboard'
#ACCOUNT_FORMS = {'signup': 'Online_Emporium.forms.CustomSignupForm1'}
#ACCOUNT_SIGNUP_FORM_CLASS = 'Online_Emporium.forms.CustomSignupForm1'

AUTHENTICATION_CLASSES = (
    # ...
    'allauth.socialaccount.providers.google.authentication.GoogleAuthentication',
)



STRIPE_PUBLIC_KEY = 'pk_test_51OAs16BcjQz7F5SUB4a1hisXJfrs9Q4hqulsKzSdOSFPq0RNv1butFhJocIbojZWMINQRbzC34fbKzrX094kq2HD00g17amJs5'
STRIPE_PUBLISHABLE_KEY = 'pk_test_51OAs16BcjQz7F5SUB4a1hisXJfrs9Q4hqulsKzSdOSFPq0RNv1butFhJocIbojZWMINQRbzC34fbKzrX094kq2HD00g17amJs5'
STRIPE_SECRET_KEY = 'sk_test_51OAs16BcjQz7F5SUVrizDWZOgYVHHMULYJ6bdEnrYfb1ORh3D5KzDawXEq2CD7FMTkBsU3wAjGfne7CynaoGEDeb00ZSUkOzYc'


STRIPE_TEST_SECRET_KEY = "sk_test_51OAs16BcjQz7F5SUVrizDWZOgYVHHMULYJ6bdEnrYfb1ORh3D5KzDawXEq2CD7FMTkBsU3wAjGfne7CynaoGEDeb00ZSUkOzYc"
STRIPE_LIVE_MODE = False  # Change to True in production
DJSTRIPE_WEBHOOK_SECRET = "whsec_B2s8G4mPvN33cMkz0UIsRoUjkBe0XR2M"
STRIPE_ENDPOINT_SECRET = "whsec_B2s8G4mPvN33cMkz0UIsRoUjkBe0XR2M"
DJSTRIPE_FOREIGN_KEY_TO_FIELD = "id"
