# Generated by Django 4.2.4 on 2023-08-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('star_ratings', models.FloatField()),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('details_page_url', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
