# Generated by Django 4.2.4 on 2023-08-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0003_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
