# Generated by Django 4.2.4 on 2023-08-12 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details_page_url',
        ),
    ]
