# Generated by Django 4.2.4 on 2023-08-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0006_rename_is_free_shipping_product_free_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
