# Generated by Django 4.2.4 on 2023-08-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='star_ratings',
            field=models.IntegerField(),
        ),
    ]
