# Generated by Django 4.2.4 on 2023-08-19 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0011_product_d_image_1_product_d_image_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Online_Emporium.product')),
                ('ram', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=20)),
                ('generation', models.CharField(max_length=10)),
            ],
            bases=('Online_Emporium.product',),
        ),
    ]
