# Generated by Django 4.2.4 on 2023-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0013_mobilephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilephone',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='MobilePhone',
        ),
    ]
