# Generated by Django 4.2.4 on 2023-08-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0015_clothes_laptop_mobile_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='product_ptr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
