# Generated by Django 4.2.4 on 2023-08-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0017_productattribute_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='data_files/'),
        ),
    ]
