# Generated by Django 4.2.4 on 2023-08-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0018_product_data_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data_file',
        ),
    ]
