# Generated by Django 4.2.4 on 2023-08-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0020_productdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
