# Generated by Django 4.2.4 on 2023-08-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0021_remove_product_attributes_delete_productattribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetail',
        ),
    ]
