# Generated by Django 4.2.4 on 2023-08-21 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0022_delete_productdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Online_Emporium.product')),
                ('ram', models.CharField(default=None, max_length=50)),
                ('storage', models.CharField(default=None, max_length=50)),
                ('generation', models.CharField(default=None, max_length=50)),
                ('processor', models.CharField(default=None, max_length=50)),
                ('gpu', models.CharField(default=None, max_length=50)),
                ('condition', models.CharField(default=None, max_length=50)),
            ],
            bases=('Online_Emporium.product',),
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Online_Emporium.product')),
                ('ram', models.CharField(default=None, max_length=50)),
                ('storage', models.CharField(default=None, max_length=50)),
                ('battery', models.CharField(default=None, max_length=50)),
                ('condition', models.CharField(default=None, max_length=50)),
                ('warranty', models.CharField(default=None, max_length=50)),
            ],
            bases=('Online_Emporium.product',),
        ),
        migrations.CreateModel(
            name='Pant',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Online_Emporium.product')),
                ('color', models.CharField(default=None, max_length=50)),
                ('size', models.CharField(default=None, max_length=10)),
                ('material', models.CharField(default=None, max_length=50)),
                ('type', models.CharField(default=None, max_length=50)),
            ],
            bases=('Online_Emporium.product',),
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Online_Emporium.product')),
                ('color', models.CharField(default=None, max_length=50)),
                ('apparel_type', models.CharField(default=None, max_length=50)),
                ('size', models.CharField(default=None, max_length=10)),
                ('material', models.CharField(default=None, max_length=50)),
            ],
            bases=('Online_Emporium.product',),
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Online_Emporium.product')),
                ('color', models.CharField(default=None, max_length=50)),
                ('size', models.CharField(default=None, max_length=10)),
                ('material', models.CharField(default=None, max_length=50)),
                ('type', models.CharField(default=None, max_length=50)),
                ('apparel_type', models.CharField(default=None, max_length=50)),
            ],
            bases=('Online_Emporium.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
