# Generated by Django 4.2.4 on 2023-08-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0023_laptop_mobilephone_pant_shirt_shoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('mobile_phone', 'Mobile Phone'), ('shirt', 'Shirt'), ('pant', 'Pants'), ('shoes', 'Shoes')], default=None, max_length=50),
        ),
    ]
