# Generated by Django 4.2.4 on 2023-08-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0026_alter_product_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoes',
        ),
    ]
