# Generated by Django 4.2.4 on 2023-08-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0028_delete_pant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shirt',
        ),
    ]
