# Generated by Django 4.2.4 on 2023-08-23 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0030_delete_mobilephone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
