# Generated by Django 4.2.4 on 2023-08-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0031_delete_laptop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='apparel_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='battery',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='generation',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='gpu',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
