# Generated by Django 4.2.4 on 2023-08-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0033_remove_product_type_product_pant_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='d_image_1',
            new_name='details_image_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='d_image_2',
            new_name='details_image_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='d_image_3',
            new_name='details_image_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='d_image_4',
            new_name='details_image_4',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='d_image_5',
            new_name='details_image_5',
        ),
    ]
