# Generated by Django 4.2.4 on 2023-08-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0034_rename_d_image_1_product_details_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='star_ratings',
            new_name='ratings',
        ),
    ]
