# Generated by Django 4.2.4 on 2023-09-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0036_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='apparel_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='details_image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='details_image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='details_image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='details_image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='details_image_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pant_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pant_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoes_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50)),
                ('attribute_value', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Emporium.product')),
            ],
        ),
    ]
