# Generated by Django 4.2.4 on 2023-09-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0039_customuser_adminrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='AdminRequest',
        ),
        migrations.DeleteModel(
            name='customuser',
        ),
    ]
