# Generated by Django 4.2.4 on 2023-10-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0045_remove_customuser_provence_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_admin',
            new_name='is_customer',
        ),
    ]
