# Generated by Django 4.2.4 on 2023-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0048_customuser_gender_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.TextField(blank=True),
        ),
    ]
