# Generated by Django 4.2.4 on 2023-10-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0051_cart_cartitem_coupon_order_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
