# Generated by Django 4.2.4 on 2023-10-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0053_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='Online_Emporium.cartitem'),
        ),
    ]
