# Generated by Django 4.2.4 on 2023-10-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0056_alter_orderitem_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Online_Emporium.cartitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Emporium.order'),
        ),
    ]
