# Generated by Django 4.2.4 on 2023-10-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0057_alter_order_order_id_alter_orderitem_cart_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(blank=True, related_name='orders', to='Online_Emporium.product'),
        ),
    ]
