# Generated by Django 4.2.4 on 2023-10-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0059_remove_order_ordered_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_products',
            field=models.ManyToManyField(blank=True, related_name='orders', to='Online_Emporium.product'),
        ),
    ]
