# Generated by Django 4.2.4 on 2023-10-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0060_order_ordered_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
