# Generated by Django 4.2.4 on 2023-10-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0063_remove_order_ordered_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_quantity',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
