# Generated by Django 4.2.7 on 2023-11-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Emporium', '0064_order_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
